import type { NextPage } from 'next';
import Head from 'next/head';

const Main: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Blog ???</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default Main;
